// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugvtabayialprmjmecej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVndnRhYmF5aWFscHJtam1lY2VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMzQ1MjEsImV4cCI6MjA1NTgxMDUyMX0.EXRUKbmZP1p1hn9eh5ua4OChACKEm2QxQkE4GTNxaJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);